"""change column name

Revision ID: 8e811eafa515
Revises: 5b71a1567bad
Create Date: 2022-12-31 11:34:49.147733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e811eafa515'
down_revision = '5b71a1567bad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decision_makers', sa.Column('organization', sa.String(), nullable=False))
    op.drop_column('decision_makers', 'affiliation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decision_makers', sa.Column('affiliation', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('decision_makers', 'organization')
    # ### end Alembic commands ###
