"""add published column to Focus table

Revision ID: a4f97c554b5d
Revises: 8e811eafa515
Create Date: 2022-12-31 13:13:45.907935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4f97c554b5d'
down_revision = '8e811eafa515'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('focus_issues', sa.Column('published', sa.Boolean(), server_default='True', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('focus_issues', 'published')
    # ### end Alembic commands ###
